### PR TITLE
Add clarification on the  prefix

### PR DESCRIPTION
**Pull request by aturkewi**
Resolves the part of issue #2 that deals with this lab.

### CODE REVIEW

**Comment by aturkewi** [comment]
@ipc103 @PeterBell

**Comment by PeterBell** [comment]
LGMT :+1: @aturkewi  Although as a Brit I'm deeply offended about you breaking the spelling of behaviour :smile_cat: Seriously, I'm gonna merge. Looks solid.

**Comment by toddmotto** [comment]
As the brit that wrote it, I'm deeply offended too ;)

**Comment by PeterBell** [comment]
:+1: @toddmotto :smile_cat:

**Pull request merged**
